### model
model_name_or_path: /root/autodl-tmp/llm-research/meta-llama-3___1-8b-instruct

### method
stage: sft
do_train: true
finetuning_type: sft
lora_target: all
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: abc
template: llama3
cutoff_len: 20000
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3/lora/sft
logging_steps: 10
save_steps: 5000000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500